type LegacyRedirect = {
  source: string;
  destination: string;
  statusCode: 301;
};

export const blogPostRedirects: LegacyRedirect[] = [
  { source: "/it/post/luna-nuova-in-toro-16-maggio-2026-semina-quello-che-vuoi-davvero-sostenere", destination: "/it/blog/luna-nuova-in-toro-16-maggio-2026-semina-quello-che-vuoi-davvero-sostenere", statusCode: 301 },
  { source: "/es/post/luna-nueva-en-tauro-16-de-mayo-2026-siembra-lo-que-quieres-sostener-de-verdad", destination: "/es/blog/luna-nueva-en-tauro-16-de-mayo-2026-siembra-lo-que-quieres-sostener-de-verdad", statusCode: 301 },
  { source: "/it/post/luna-piena-in-scorpione-1-maggio-2026-quello-che-non-volevi-vedere-non-puo-piu-aspettare", destination: "/it/blog/luna-piena-in-scorpione-1-maggio-2026-quello-che-non-volevi-vedere-non-puo-piu-aspettare", statusCode: 301 },
  { source: "/es/post/luna-llena-escorpio-1-mayo-2026", destination: "/es/blog/luna-llena-escorpio-1-mayo-2026", statusCode: 301 },
  { source: "/it/post/ariete-in-fiamme-come-lo-stellium-di-aprile-2026-sta-trasformando-la-tua-identi", destination: "/it/blog/ariete-in-fiamme-come-lo-stellium-di-aprile-2026-sta-trasformando-la-tua-identi", statusCode: 301 },
  { source: "/es/post/aries-en-llamas-como-el-stellium-de-abril-2026-esta-transformando-tu-identidad", destination: "/es/blog/aries-en-llamas-como-el-stellium-de-abril-2026-esta-transformando-tu-identidad", statusCode: 301 },
  { source: "/it/post/luna-piena-bilancia-aprile-2026-relazioni-transiti-astrologici", destination: "/it/blog/luna-piena-bilancia-aprile-2026-relazioni-transiti-astrologici", statusCode: 301 },
  { source: "/es/post/impacto-de-la-luna-llena-en-libra-del-2-de-abril-en-tu-vida-y-relaciones", destination: "/es/blog/impacto-de-la-luna-llena-en-libra-del-2-de-abril-en-tu-vida-y-relaciones", statusCode: 301 },
  { source: "/it/post/i-3-cicli-di-navratri-e-il-loro-significato-spirituale", destination: "/it/blog/i-3-cicli-di-navratri-e-il-loro-significato-spirituale", statusCode: 301 },
  { source: "/es/post/navratri-9-noches-para-transformar-nutrir-y-elevar-la-energia", destination: "/es/blog/navratri-9-noches-para-transformar-nutrir-y-elevar-la-energia", statusCode: 301 },
  { source: "/it/post/luna-nuova-in-pesci-28-19-marzo-2026", destination: "/it/blog/luna-nuova-in-pesci-28-19-marzo-2026", statusCode: 301 },
  { source: "/es/post/luna-nueva-en-piscis", destination: "/es/blog/luna-nueva-en-piscis", statusCode: 301 },
  { source: "/it/post/iranterzoocchiodellaterrasimbolismospirituale", destination: "/it/blog/iranterzoocchiodellaterrasimbolismospirituale", statusCode: 301 },
  { source: "/es/post/iran-el-tercer-ojo-y-la-batalla-invisible-por-la-conciencia-del-mundo", destination: "/es/blog/iran-el-tercer-ojo-y-la-batalla-invisible-por-la-conciencia-del-mundo", statusCode: 301 },
  { source: "/it/post/una-chiusura-per-mettere-ordine-nel-cuore-luna-piena-in-vergine", destination: "/it/blog/una-chiusura-per-mettere-ordine-nel-cuore-luna-piena-in-vergine", statusCode: 301 },
  { source: "/es/post/un-cierre-para-ordenar-el-corazon-luna-llena-en-virgo", destination: "/es/blog/un-cierre-para-ordenar-el-corazon-luna-llena-en-virgo", statusCode: 301 },
  { source: "/it/post/chiave-psicologica-di-saturno-in-ariete", destination: "/it/blog/chiave-psicologica-di-saturno-in-ariete", statusCode: 301 },
  { source: "/es/post/clave-psicologica-de-saturno-en-aries", destination: "/es/blog/clave-psicologica-de-saturno-en-aries", statusCode: 301 },
  { source: "/it/post/le-fasi-di-mercurio-retrogrado-e-il-suo-linguaggio-pre-ombra-retrogradazione-e-post-ombra", destination: "/it/blog/le-fasi-di-mercurio-retrogrado-e-il-suo-linguaggio-pre-ombra-retrogradazione-e-post-ombra", statusCode: 301 },
  { source: "/es/post/las-fases-de-mercurio-retrogrado-y-su-lenguaje-pre-sombra-retrogradacion-y-post-sombra", destination: "/es/blog/las-fases-de-mercurio-retrogrado-y-su-lenguaje-pre-sombra-retrogradacion-y-post-sombra", statusCode: 301 },
  { source: "/it/post/la-storia-del-cielo-che-si-ripete", destination: "/it/blog/la-storia-del-cielo-che-si-ripete", statusCode: 301 },
  { source: "/es/post/el-cuento-del-cielo-que-se-repite", destination: "/es/blog/el-cuento-del-cielo-que-se-repite", statusCode: 301 },
  { source: "/it/post/cambiamento-interiore-2025-2026-astrologia-psicologica-per-comprendere-una-nuova-fase-di-coscien", destination: "/it/blog/cambiamento-interiore-2025-2026-astrologia-psicologica-per-comprendere-una-nuova-fase-di-coscien", statusCode: 301 },
  { source: "/es/post/cambio-interior-2025-2026", destination: "/es/blog/cambio-interior-2025-2026", statusCode: 301 },
  { source: "/it/post/la-fine-del-ciclo-un-viaggio-psicologico-di-dissoluzione-confini-e-resa", destination: "/it/blog/la-fine-del-ciclo-un-viaggio-psicologico-di-dissoluzione-confini-e-resa", statusCode: 301 },
  { source: "/es/post/final-de-etapa-un-viaje-psicologico-de-disolucion-limites-y-rendicion", destination: "/es/blog/final-de-etapa-un-viaje-psicologico-de-disolucion-limites-y-rendicion", statusCode: 301 },
  { source: "/it/post/mi-permetto-di-pensare-in-modo-diverso", destination: "/it/blog/mi-permetto-di-pensare-in-modo-diverso", statusCode: 301 },
  { source: "/post/i-allow-myself-to-think-differently", destination: "/es/blog/luna-llena-en-geminis-me-permito-pensar-diferente", statusCode: 301 },
  { source: "/es/post/luna-llena-en-geminis-me-permito-pensar-diferente", destination: "/es/blog/luna-llena-en-geminis-me-permito-pensar-diferente", statusCode: 301 },
  { source: "/it/post/luna-nuova-in-scorpione-28-un-inizio-che-nasce-dalla-fine", destination: "/it/blog/luna-nuova-in-scorpione-28-un-inizio-che-nasce-dalla-fine", statusCode: 301 },
  { source: "/es/post/luna-nueva-en-escorpio-28-un-comienzo-que-nace-del-final", destination: "/es/blog/luna-nueva-en-escorpio-28-un-comienzo-que-nace-del-final", statusCode: 301 },
  { source: "/it/post/coraggio-dal-tangibile-allinvisibile", destination: "/it/blog/coraggio-dal-tangibile-allinvisibile", statusCode: 301 },
  { source: "/es/post/el-valor-de-lo-tangible-a-lo-invisible", destination: "/es/blog/el-valor-de-lo-tangible-a-lo-invisible", statusCode: 301 },
  { source: "/es/post/transformar-los-limites-en-poder-el-renacer-interior-bajo-pluton-en-acuario", destination: "/es/blog/transformar-los-limites-en-poder-el-renacer-interior-bajo-pluton-en-acuario", statusCode: 301 },
  { source: "/it/post/luna-piena-in-ariete-e-plutone-diretto-in-acquario-il-fuoco-dell-anima-che-risveglia-la-coscienz", destination: "/it/blog/luna-piena-in-ariete-e-plutone-diretto-in-acquario-il-fuoco-dell-anima-che-risveglia-la-coscienz", statusCode: 301 },
  { source: "/es/post/luna-llena-en-aries-y-pluton-directo-en-acuario-el-fuego-del-alma-que-despierta-la-conciencia-co", destination: "/es/blog/luna-llena-en-aries-y-pluton-directo-en-acuario-el-fuego-del-alma-que-despierta-la-conciencia-co", statusCode: 301 },
  { source: "/es/post/eldespertardelaconcienciaenelpresente", destination: "/es/blog/eldespertardelaconcienciaenelpresente", statusCode: 301 },
  { source: "/it/post/macrocosmo-e-microcosmo-il-risveglio-della-coscienza-nel-presente", destination: "/it/blog/macrocosmo-e-microcosmo-il-risveglio-della-coscienza-nel-presente", statusCode: 301 },
  { source: "/es/post/duelo-y-transformacion-espiritual-en-tiempos-de-eclipses", destination: "/es/blog/duelo-y-transformacion-espiritual-en-tiempos-de-eclipses", statusCode: 301 },
  { source: "/es/post/luna-nueva-en-virgo-23-de-agosto-2025", destination: "/es/blog/luna-nueva-en-virgo-23-de-agosto-2025", statusCode: 301 },
  { source: "/it/post/alta-sensilibita", destination: "/it/blog/alta-sensilibita", statusCode: 301 },
  { source: "/es/post/el-poder-de-mi-alta-sensibilidad-de-la-vulnerabilidad-al-superpoder", destination: "/es/blog/el-poder-de-mi-alta-sensibilidad-de-la-vulnerabilidad-al-superpoder", statusCode: 301 },
  { source: "/it/post/yoga-terapeutico-e-astrologia-psicologica-l-unione-degli-elementi-e-dei-chakra", destination: "/it/blog/yoga-terapeutico-e-astrologia-psicologica-l-unione-degli-elementi-e-dei-chakra", statusCode: 301 },
  { source: "/es/post/yoga-terapeutico-y-astrologia-psicologica-la-union-de-los-elementos-y-los-chakras", destination: "/es/blog/yoga-terapeutico-y-astrologia-psicologica-la-union-de-los-elementos-y-los-chakras", statusCode: 301 },
  { source: "/it/post/urano-in-gemelli-e-iniziata-la-rivoluzione-mentale", destination: "/it/blog/urano-in-gemelli-e-iniziata-la-rivoluzione-mentale", statusCode: 301 },
  { source: "/es/post/urano-en-geminis-la-revolucion-mental-ha-comenzado", destination: "/es/blog/urano-en-geminis-la-revolucion-mental-ha-comenzado", statusCode: 301 },
  { source: "/es/post/luna-llena-en-capricornio-gurupoornima", destination: "/es/blog/luna-llena-en-capricornio-gurupoornima", statusCode: 301 },
  { source: "/it/post/luna-piena-in-capricorno-gurupoornima", destination: "/it/blog/luna-piena-in-capricorno-gurupoornima", statusCode: 301 },
  { source: "/es/post/luna-llena-en-sagitario-despedida-con-gratitud-y-apertura-a-lo-nuevo", destination: "/es/blog/luna-llena-en-sagitario-despedida-con-gratitud-y-apertura-a-lo-nuevo", statusCode: 301 },
  { source: "/es/post/revelaciones-cierres-y-transformacion-profunda-astrologia-pscologica", destination: "/es/blog/revelaciones-cierres-y-transformacion-profunda-astrologia-pscologica", statusCode: 301 },
  { source: "/post/new-roots-new-moon-in-taurus-and-the-path-to-authenticity", destination: "/es/blog/sembrando-desde-el-corazon-luna-nueva-en-tauro-y-el-despertar-de-nuestra-verdadera-estabilidad", statusCode: 301 },
  { source: "/es/post/sembrando-desde-el-corazon-luna-nueva-en-tauro-y-el-despertar-de-nuestra-verdadera-estabilidad", destination: "/es/blog/sembrando-desde-el-corazon-luna-nueva-en-tauro-y-el-despertar-de-nuestra-verdadera-estabilidad", statusCode: 301 },
  { source: "/es/post/el-arte-de-amarnos-en-libertad", destination: "/es/blog/el-arte-de-amarnos-en-libertad", statusCode: 301 },
  { source: "/es/post/un-nuevo-comienzo-y-el-fin-de-un-ciclo-luna-nueva-y-eclipse-solar-en-aries", destination: "/es/blog/un-nuevo-comienzo-y-el-fin-de-un-ciclo-luna-nueva-y-eclipse-solar-en-aries", statusCode: 301 },
  { source: "/es/post/el-equinoccio-de-primavera-2025-una-puerta-hacia-la-renovacion-interior", destination: "/es/blog/el-equinoccio-de-primavera-2025-una-puerta-hacia-la-renovacion-interior", statusCode: 301 },
  { source: "/post/eclipse-with-south-node-in-virgo-and-full-moon-on-march-14-2025-a-call-to-integrate-chaos-and-or", destination: "/es/blog/eclipseenvirgo2025", statusCode: 301 },
  { source: "/post/eclipse-with-south-node-in-virgo-and-full-moon-on-march-14-2025-a-call-to-integrate-chaos-and-order", destination: "/es/blog/eclipseenvirgo2025", statusCode: 301 },
  { source: "/es/post/eclipseenvirgo2025", destination: "/es/blog/eclipseenvirgo2025", statusCode: 301 },
  { source: "/es/post/taller-el-arte-de-comunicar", destination: "/es/blog/taller-el-arte-de-comunicar", statusCode: 301 },
  { source: "/es/post/retrogradacion-de-un-planeta-que-activa-a-nivel-pscologico", destination: "/es/blog/retrogradacion-de-un-planeta-que-activa-a-nivel-pscologico", statusCode: 301 },
  { source: "/es/post/lunallenaenleobrillaconautenticidad", destination: "/es/blog/lunallenaenleobrillaconautenticidad", statusCode: 301 },
  { source: "/post/fullmooninleoshinewithauthenticity", destination: "/es/blog/lunallenaenleobrillaconautenticidad", statusCode: 301 },
  { source: "/es/post/un-desafio-para-cuerpo-y-mente-sumergirse-en-el-mar-en-invierno", destination: "/es/blog/un-desafio-para-cuerpo-y-mente-sumergirse-en-el-mar-en-invierno", statusCode: 301 },
  { source: "/es/post/laghoo-shankhaprakshalana-purificacion-del-intestino-y-del-inconsciente", destination: "/es/blog/laghoo-shankhaprakshalana-purificacion-del-intestino-y-del-inconsciente", statusCode: 301 },
  { source: "/es/post/ano-nuevo-chino-transformacio-renacimiento-astro", destination: "/es/blog/ano-nuevo-chino-transformacio-renacimiento-astro", statusCode: 301 },
  { source: "/es/post/iluminando-la-sombra-y-redefiniendo-nuestros-ideales", destination: "/es/blog/iluminando-la-sombra-y-redefiniendo-nuestros-ideales", statusCode: 301 },
  { source: "/es/post/conjuncion-lilith-venus-en-libra-explorando-sombras-y-deseos-en-las-relaciones", destination: "/es/blog/conjuncion-lilith-venus-en-libra-explorando-sombras-y-deseos-en-las-relaciones", statusCode: 301 },
  { source: "/es/post/como-practicar-la-atencion-plena", destination: "/es/blog/como-practicar-la-atencion-plena", statusCode: 301 },
  { source: "/es/post/embarazo-espiritual", destination: "/es/blog/embarazo-espiritual", statusCode: 301 },
  { source: "/es/post/centros-budistas-en-barcelona", destination: "/es/blog/centros-budistas-en-barcelona", statusCode: 301 },
  { source: "/es/post/respiracion-de-fuego-como-hacerla-correctamente", destination: "/es/blog/respiracion-de-fuego-como-hacerla-correctamente", statusCode: 301 },
  { source: "/es/post/el-significado-del-ascendente-en-la-astrologia-psicologica", destination: "/es/blog/el-significado-del-ascendente-en-la-astrologia-psicologica", statusCode: 301 },
  { source: "/post/astrological-coaching", destination: "/es/blog/coaching-astrologico", statusCode: 301 },
  { source: "/es/post/coaching-astrologico", destination: "/es/blog/coaching-astrologico", statusCode: 301 },
  { source: "/es/post/que-es-el-yoga-nidra-una-guia-completa", destination: "/es/blog/que-es-el-yoga-nidra-una-guia-completa", statusCode: 301 },
  { source: "/es/post/que-es-el-kundalini-yoga", destination: "/es/blog/que-es-el-kundalini-yoga", statusCode: 301 },
  { source: "/post/:slug", destination: "/es/blog/:slug", statusCode: 301 },
  { source: "/es/post/:slug", destination: "/es/blog/:slug", statusCode: 301 },
  { source: "/it/post/:slug", destination: "/it/blog/:slug", statusCode: 301 },
];
